job/Boss/urls.py
from django.urls import path,re_path
from Boss.views import *

urlpatterns = [
	re_path('index/(?P<page>\d+)',index),
	path('logout/',logout),

	path('add_job/',add_job),

	path('record/',record),
	path('boss_info/',boss_info),
	path('update/',update),
	path('company/',company),
	path('check/',check),
	path('invate/',invate),
	path('operate/',operate),
	path('delete_job/',delete_job),
	path('job_publish/',job_publish),
	re_path('job_list/(?P<status>[0123])/(?P<page>\d+)',job_list),
	re_path('send_status/(?P<status>[012345678])/(?P<page>\d+)',send_status),
]

job/job/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',register),
    path('login/',login),
    path('forget/',forget),
    path('index/',index),
    path('Graduate/',include("Graduate.urls")),
    path('Boss/',include("Boss.urls")),
    path('Admins/',include("Admins.urls"))
]

job/Boss/models.py
from django.db import models

# Create your models here.

# 企业性质表
class C_type(models.Model):
	type = models.CharField(max_length=64,verbose_name="企业性质")

	class Meta:
		db_table = 'c_type'


# 企业表
# 经营状态
MANAGE_STATUS = (
	(0,"存续(开业、正常、登记)"),
	(1,"在业"),
	(2,"吊销"),
	(3,"注销"),
	(4,"迁出"),
	(5,"迁入"),
	(6,"停业"),
	(7,"清算"),
	)
# 职员人数
STAFF_NUM = (
	(0,"少于10人"),
	(1,"10-49人"),
	(2,"50-99人"),
	(3,"100-499人"),
	(4,"500-999人"),
	(5,"1000-9999人"),
	(6,"10000人以上")
)

class Company(models.Model):
	c_email = models.EmailField(verbose_name='企业邮箱')
	c_name = models.CharField(max_length=32, verbose_name='企业名')
	phone_number = models.CharField(max_length=11, verbose_name='企业电话')
	c_code = models.CharField(max_length=32,verbose_name='统一信用代码')
	c_legal = models.CharField(max_length=32,verbose_name='企业法人')
	c_photo = models.ImageField(upload_to='images', verbose_name='企业照片')
	# 注册资本,单位：万元
	c_money = models.IntegerField(verbose_name='注册资本')
	c_status = models.IntegerField(choices=MANAGE_STATUS,verbose_name='经营状态')
	c_time = models.DateField(verbose_name='成立时间')
	c_address = models.TextField(verbose_name='注册地址')
	c_scope = models.TextField(verbose_name='经营范围')
	c_website = models.TextField(verbose_name='公司官网')
	c_descript = models.TextField(verbose_name='公司简介')
	# 公司人员
	c_staff = models.IntegerField(null=True,blank=True,choices=STAFF_NUM,verbose_name='职员人数')
	# 外键公司性质
	c_type = models.ForeignKey(null=True,blank=True,to=C_type,on_delete=models.CASCADE)

	class Meta:
		db_table = 'company'

# 招聘者现工作岗位信息
# 在职信息
WORK_STATUS = (
	(0,'在职'),
	(1,'离职'),
	(2,'停职'),
)

# 招聘者表
class Boss(models.Model):
	email = models.EmailField(verbose_name='邮箱', default=0)
	password = models.CharField(max_length=32, verbose_name='密码')
	name = models.CharField(max_length=32, null=True, blank=True, verbose_name='招聘者名')
	## null 针对数据库，可以为空
	## blank针对表单，表示在表单中该字段可以不填，对数据库没有影响
	phone = models.CharField(max_length=11, null=True, blank=True, verbose_name='手机号')
	## type 中
	## 0 代表求职者
	## 1 代表企业
	## 2 代表管理员
	type = models.CharField(max_length=4,null=True, blank=True, verbose_name='类别')
	photo = models.ImageField(upload_to='images', null=True, blank=True, verbose_name='头像')
	age = models.IntegerField(null=True, blank=True, verbose_name='年龄')
	gender = models.CharField(max_length=4, null=True, blank=True, verbose_name='性别')
	address = models.TextField(null=True, blank=True, verbose_name='居住地')
	work_status = models.IntegerField(null=True, blank=True,choices=WORK_STATUS, verbose_name='在职信息')
	professional_title = models.CharField(null=True, blank=True, max_length=32, verbose_name='职称')
	work_experience = models.TextField(null=True, blank=True, verbose_name='工作经验')
	# 外键，对应公司
	b_company = models.ForeignKey(null=True,blank=True,to=Company,on_delete=models.CASCADE)

	class Meta:
		db_table = 'boss'

# 城市表
class City(models.Model):
	name = models.CharField(max_length=32)

	class Meta:
		db_table = 'city'


# 职位表
# 学历
EDUCATION = (
	(0,'大专'),
	(1,'本科'),
	(2,'硕士'),
	(3,'博士'),
)
# 审核状态
REVIEW_STATUS = (
	(0,"待审核"),
	(1,"审核中"),
	(2,"已发布"),
	(3,"审核未通过"),
	(4,"已删除"),
	)

class Job(models.Model):
	job_name = models.CharField(max_length=32, verbose_name='职位名称')
	job_address = models.TextField(verbose_name='工作地点')
	education = models.IntegerField(choices=EDUCATION,verbose_name='学历')
	pay = models.CharField(max_length=20,verbose_name='薪资')
	job_descript = models.TextField(null=True,blank=True,verbose_name='岗位详情')
	demand = models.TextField(verbose_name='任职要求')
	work_time = models.TextField(verbose_name='工作时间')
	# 发布时间
	time = models.DateTimeField(auto_now=True,null=True,blank=True,verbose_name='发布时间')
	# 职位诱惑/标签   注意：在文本框中必须以逗号分割
	job_label = models.TextField(verbose_name='标签')
	# 管理员审核状态
	check_status = models.IntegerField(null=True, blank=True, choices=REVIEW_STATUS, verbose_name="审核状态")
	# 外键，对应城市,改职位在哪个城市下
	city = models.ForeignKey(to=City,on_delete=models.CASCADE,default=1)
	# 外键，对应公司
	j_company = models.ForeignKey(to=Company,on_delete=models.CASCADE)
	# 外键，对应hr
	b_boss = models.ForeignKey(to=Boss,on_delete=models.CASCADE)

	class Meta:
		db_table = 'job'

# 职位下投递情况表
# 投递状态
SEND_STATUS = (
	(0,'未查看'),
	(1,'已查看'),
	(2,'已发送邀请'),
	(3,'邀请面试成功'),
	(4,'不合适'),
	(5,'邀请面试失败'),
	(6,'面试通过'),
	(7,'面试未通过'),
	(8,'录用通知已发送'),
)

class Job_table(models.Model):
	# 投递者
	h_name = models.ForeignKey(to="Graduate.Hunter",on_delete=models.CASCADE)
	# 职位名
	j_name = models.ForeignKey(to=Job,on_delete=models.CASCADE,null=True,blank=True)
	time = models.DateTimeField(verbose_name='投递时间')
	send_status = models.IntegerField(choices=SEND_STATUS,verbose_name='投递状态')

	class Meta:
		db_table = 'job_table'

job/Boss/views.py
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.core.paginator import Paginator
from django.shortcuts import render
from email.mime.text import MIMEText
from .models import *
import hashlib, random, datetime, smtplib


# Create your views here.

## 登录装饰器
def LoginVaild(func):
	## 1. 获取cookie中username和email
	## 2. 判断username和email
	## 3. 如果成功  跳转
	## 4. 如果失败   login.html
	def inner(request, *args, **kwargs):
		useremail = request.COOKIES.get('useremail')
		usertype = request.COOKIES.get("usertype")
		## 获取session
		session_useremail = request.session.get("useremail")
		session_type = request.session.get("usertype")
		if useremail and session_useremail and usertype and session_type and useremail == session_useremail and usertype == session_type and Boss.objects.filter(
				email=useremail, type=usertype).first():
			return func(request, *args, **kwargs)
		else:
			return HttpResponseRedirect('/login/')

	return inner


## 密码加密
def setPassword(password):
	## 实现一个密码加密
	md5 = hashlib.md5()  ## 创建一个md5的实例对象
	md5.update(password.encode())  ## 进行加密
	result = md5.hexdigest()
	return result


# 发送邮件
def send_email(email, subject, content):
	subject = subject
	content = content
	sender = "bx1125666@163.com"
	rec = email
	password = "bx19980105bx"
	###  MIMEText 参数 发送内容， 内容类型 , 编码
	message = MIMEText(content, "plain", "utf-8")
	message["Subject"] = subject
	message["From"] = sender
	message["To"] = rec

	smtp = smtplib.SMTP_SSL("smtp.163.com", 465)
	smtp.login(sender, password)
	## 参数说明：发件人，收件人(一个列表/单个)     发送邮件 类似一种json的格式
	smtp.sendmail(sender, rec, message.as_string())
	smtp.close()
	result = {"code": 10000, "msg": "面试邀请已发送"}
	return result


# 获取当前登录用户
@LoginVaild
def get_user(request):
	useremail = request.COOKIES.get('useremail')
	usertype = request.COOKIES.get("usertype")
	user = Boss.objects.filter(email=useremail, type=usertype).first()
	return user


## 登出
@LoginVaild
def logout(request):
	response = HttpResponseRedirect("/login/")
	keys = request.COOKIES.keys()
	for one in keys:
		response.delete_cookie(one)

	del request.session['useremail']
	del request.session['usertype']
	return response


# 主页
@LoginVaild
def index(request, page):
	page = int(page)
	user = get_user(request)
	job = Job.objects.filter(b_boss_id=user.id).all()
	# 主页显示为投递简历未面试邀请的或者未点击不合适的；可操作邀请或者拒绝
	job_obj = Job_table.objects.filter(j_name__in=job, send_status__lte=2).order_by("time")

	job_all = Paginator(job_obj, 10)
	job_list = job_all.page(page)
	current_page = job_list.number
	start = current_page - 3
	if start < 1:
		start = 0
	end = current_page + 2
	if end > job_all.num_pages:
		end = job_all.num_pages
	if start == 0:
		end = 5
	page_range = job_all.page_range[start:end]

	return render(request, "boss/index.html", locals())


# 个人信息页
@LoginVaild
# 个人信息页
def boss_info(request):
	user = get_user(request)
	work_status = user.get_work_status_display()
	if request.method == "POST":
		# 	# 获取表单信息，存入数据库
		data = request.POST
		user.name = data.get("name")
		user.phone = data.get("phone")
		user.age = data.get("age")
		user.gender = data.get("gender")
		user.address = data.get("address")
		user.photo = request.FILES.get('photo')
		user.save()
	return render(request, "boss/boss_info.html", locals())


# 资历资料
def record(request):
	user = get_user(request)
	company = Company.objects.all()
	if request.method == "POST":
		data = request.POST
		user.work_status = int(data.get("work_status"))
		user.professional_title = data.get("professional_title")
		user.work_experience = data.get("work_experience")
		c_id = data.get("company")
		try:
			if int(c_id):
				user.b_company = Company.objects.get(id=int(c_id))
		except:
			pass
		user.save()
	return render(request, 'boss/record.html', locals())


# 修改密码
def update(request):
	user = get_user(request)
	if request.method == "POST":
		data = request.POST
		update = data.get("update_password")
		update1 = data.get("update_password1")
		if update and update1 and update == update1:
			user.password = setPassword(update)
			user.save()
	return render(request, 'boss/update_password.html', locals())


# 增加公司/完善公司信息
def company(request):
	user = get_user(request)
	c_type = C_type.objects.all()
	if request.method == "POST":
		data = request.POST
		try:
			company = Company.objects.get(id=Boss.objects.filter(email=user.email, type=user.type).first().b_company_id)
			company.c_email = data.get("email")
			company.phone_number = data.get("phone")
			company.c_legal = data.get("legal")
			company.c_status = int(data.get("status"))
			company.c_staff = data.get("staff")
			company.c_scope = data.get("scope")
			company.c_website = data.get("website")
			company.c_descript = data.get("descript")
			company.save()

		except:
			company = Company()
			company.c_email = data.get("email")
			company.c_name = data.get("name")
			company.phone_number = data.get("phone")
			company.c_code = data.get("code")
			company.c_legal = data.get("legal")
			company.c_money = int(data.get("money"))
			company.c_status = int(data.get("status"))

			date_str = data.get("time")
			company.c_time = datetime.date(*map(int, date_str.split('-')))
			company.c_address = data.get("address")
			company.c_scope = data.get("scope")
			company.c_website = data.get("website")
			company.c_descript = data.get("descript")
			company.c_photo = request.FILES.get("photo")
			company.c_staff = data.get("staff")

			data_type = data.get("data_type")
			try:
				if int(data_type):
					company.c_type_id = int(data_type)
			except:
				type_name = data.get("type")
				if type_name:
					t = C_type()
					t.type = type_name
					t.save()
					company.c_type = C_type.objects.get(type=type_name)
			company.save()
			user.b_company_id = company.id
			user.save()
	return render(request, 'boss/company.html', locals())


# 发布职位
def job_publish(request):
	user = get_user(request)
	city = City.objects.all()
	if request.method == "POST":
		data = request.POST
		job = Job()
		job.job_name = data.get("job_name")
		job.job_address = data.get("job_address")
		job.education = int(data.get("education"))
		job.pay = data.get("pay")
		job.job_descript = data.get("job_descript")
		job.demand = data.get("demand")
		job.work_time = data.get("work_time")
		job.job_label = data.get("job_label").split("；")
		data_city = data.get("data_city")
		try:
			if int(data_city):
				job.city_id = int(data_city)
		except:
			city_name = data.get("city")
			if city_name:
				c = City()
				c.name = city_name
				c.save()
				job.city = City.objects.get(name=city_name)
		job.check_status = 0
		job.j_company_id = user.b_company.id
		job.b_boss_id = user.id
		job.save()

	return render(request, 'boss/job_publish.html', locals())


# 职位状态页
def job_list(request, status, page):
	"""
		传入参数介绍
		:param request:
		:param status:0，1，2，3
		:param page:页数
		:return:待审核，审核中，已发布，审核未通过
		"""
	user = get_user(request)
	page = int(page)
	if status == "0":
		## 待审核
		job_obj = Job.objects.filter(check_status=0, b_boss_id=user.id).order_by("time")
	elif status == "1":
		## 审核中
		job_obj = Job.objects.filter(check_status=1, b_boss_id=user.id).order_by("time")
	elif status == "2":
		## 已发布
		job_obj = Job.objects.filter(check_status=2, b_boss_id=user.id).order_by("time")
	elif status == "3":
		## 审核未通过
		job_obj = Job.objects.filter(check_status=3, b_boss_id=user.id).order_by("time")
	job_all = Paginator(job_obj, 10)
	job_list = job_all.page(page)
	current_page = job_list.number
	start = current_page - 3
	if start < 1:
		start = 0
	end = current_page + 2
	if end > job_all.num_pages:
		end = job_all.num_pages
	if start == 0:
		end = 5
	page_range = job_all.page_range[start:end]

	return render(request, 'boss/job_list.html', locals())


# 查看/修改职位信息
def check(request):
	user = get_user(request)
	id = request.GET.get("id")
	job = Job.objects.get(id=int(id))
	education = job.get_education_display()
	city = City.objects.all()
	if request.method == "POST":
		data = request.POST
		job.job_name = data.get("job_name")
		job.job_address = data.get("job_address")
		job.education = int(data.get("education"))
		job.pay = data.get("pay")
		job.job_descript = data.get("job_descript")
		job.demand = data.get("demand")
		job.work_time = data.get("work_time")
		job.job_label = data.get("job_label")
		data_city = data.get("data_city")
		try:
			if int(data_city):
				job.city_id = int(data_city)
		except:
			city_name = data.get("city")
			if city_name:
				c = City()
				c.name = city_name
				c.save()
				job.city = City.objects.get(name=city_name)
		job.check_status = 0
		job.save()

	return render(request, 'boss/job_detail.html', locals())


# 删除职位
def delete_job(request):
	if request.method == "POST":
		data = request.POST
		d_id = data.get("d_id")
		job = Job.objects.get(id=d_id)
		job.delete()
		result = {"code": 10000, "msg": "删除成功"}
	return JsonResponse(result)


# 求职者投递简历后，boss操作状态
def send_status(request, status, page):
	page = int(page)
	user = get_user(request)
	job = Job.objects.filter(b_boss_id=user.id).all()
	if status == "0":
		## 未查看
		job_obj = Job_table.objects.filter(send_status=0, j_name__in=job).order_by("time")
	elif status == "1":
		## 已查看
		job_obj = Job_table.objects.filter(send_status__gte=1, j_name__in=job).order_by("time")
	elif status == "2":
		## 已发送邀请
		job_obj = Job_table.objects.filter(send_status__in=[2, 3, 5, 6, 7, 8], j_name__in=job).order_by("time")
	elif status == "3":
		## 面试邀请成功
		job_obj = Job_table.objects.filter(send_status__in=[3, 6, 7, 8], j_name__in=job).order_by("time")
	elif status == "4":
		## 不合适
		job_obj = Job_table.objects.filter(send_status=4, j_name__in=job).order_by("time")
	elif status == "5":
		## 邀请面试失败
		job_obj = Job_table.objects.filter(send_status=5, j_name__in=job).order_by("time")
	elif status == "6":
		## 面试通过
		job_obj = Job_table.objects.filter(send_status__in=[6,8], j_name__in=job).order_by("time")
	elif status == "7":
		## 面试未通过
		job_obj = Job_table.objects.filter(send_status=7, j_name__in=job).order_by("time")

job/Boss/templates/boss/boss_info.html
{% extends "boss/base.html" %}
{% block title %}
    个人信息页
{% endblock %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-bordered dataTable" style="text-align: center">
            <thead style="font-size: 30px;font-weight: bold">
            <tr>
                <td colspan="5">基本信息</td>
            </tr>
            </thead>
            <tr>
                <td rowspan="3" style="width: 300px;">
                    <img style="width: 300px;height:300px" src="/static/{{ user.photo }}" alt="">
                    <input type="file" name="photo">
                </td>
                <th style="vertical-align: middle">邮箱</th>
                <td style="vertical-align: middle"><input type="text" name="email" value="{{ user.email }}" readonly="readonly"></td>
                <th style="vertical-align: middle">用户名</th>
                <td style="vertical-align: middle"><input type="text" name="name" value="{{ user.name }}"></td>
            </tr>
            <tr>
                <th style="vertical-align: middle">手机号</th>
                <td style="vertical-align: middle"><input type="text" name="phone" value="{{ user.phone }}"></td>

                <th style="vertical-align: middle">年龄</th>
                <td style="vertical-align: middle"><input type="text" name="age" value="{{ user.age }}"></td>
            </tr>
            <tr>
                <th style="vertical-align: middle">性别</th>
                <td style="vertical-align: middle"><input type="text" name="gender" value="{{ user.gender }}"></td>
                <th style="vertical-align: middle">地址</th>
                <td style="vertical-align: middle"><input type="text" name="address" value="{{ user.address }}"></td>
            </tr>
            <tr>
                <td colspan="5" style="text-align: center">
                    <input class="btn btn-primary " type="submit" value="完善基本信息">
                </td>
            </tr>
        </table>
    </form>
    {% if user.work_status or user.professional_title or user.work_experience %}
        <table class="table table-bordered dataTable" style="text-align: center">
            <thead>
            <tr>
                <td colspan="2" style="font-size: 30px;font-weight: bold">资历信息</td>
            </tr>
            </thead>
            <tr>
                <th>在职信息</th>
                <td>{{ work_status }}</td>
            </tr>
            <tr>
                <th>职称</th>
                <td>{{ user.professional_title }}</td>
            </tr>
            <tr>
                <th>工作经验</th>
                <td>{{ user.work_experience }}</td>
            </tr>
            <tr>
                <th>所属公司</th>
                <td><a href="/Boss/company">{{ user.b_company.c_name }}</a></td>
            </tr>
        </table>
    {% endif %}
{% endblock %}

job/Boss/templates/boss/index.html
{% extends 'boss/base.html' %}
{% block title %}
    企业hr主页
{% endblock %}

{% block content %}
    <table class="table" style="text-align: center">
            <thead>
            <tr>
                <th>公司</th>
                <th>职位名</th>
                <th>投递者</th>
                <th>时间</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for one in job_list %}

            <tr>
                <td style="vertical-align: middle">{{ one.j_name.j_company.c_name }}</td>
                <td style="vertical-align: middle">{{ one.j_name.job_name }}</td>
                <td style="vertical-align: middle">{{ one.h_name.name }}</td>
                <td style="vertical-align: middle">{{ one.time }}</td>
                <td style="vertical-align: middle">
                        <a href="/static/{{ one.h_name.resume }}" class="btn btn-primary resume" check_id="{{ one.id }}">查看简历</a>
                   {% if one.send_status == 4 %}
                        <button class="btn btn-success" disabled>面试邀请</button>
                   {% else %}
                        <a href="/Boss/invate/?i_id={{ one.id }}&page={{ page }}"><button class="btn-success">面试邀请</button></a>
                   {% endif %}

                    {% if one.send_status < 2 %}
                    <a href="/Boss/invate/?f_id={{ one.id }}&page={{ page }}"><button class="btn-danger">不合适</button></a>
{#                    <button class="btn btn-danger fail" fail_id="{{ one.id }}">不合适</button>#}
                    {% elif one.send_status == 2 or one.send_status == 3 or one.send_status == 4 %}
                        <button class="btn btn-danger" disabled>不合适</button>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
    </table>

<!--分页paginator-->
<ul class="pagination" style="float: right;position: fixed;right: 80px;bottom: 80px">
        {% if job_list.has_previous %}
            <li class="paginate_button page-item previous">
                <a href="/Boss/send_status/{{ status }}/{{ job_list.previous_page_number }}/" class="page-link">上一页</a>
            </li>
        {% endif %}
        {% for p in page_range %}
            {% if p == page %}
                <li class="paginate_button page-item previous active">
                    <a href="/Boss/send_status/{{ status }}/{{ p }}/" class="page-link">{{ p }}</a>
                </li>
            {% else %}
                <li class="paginate_button page-item previous">
                    <a href="/Boss/send_status/{{ status }}/{{ p }}/" class="page-link">{{ p }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if job_list.has_next %}
            <li class="paginate_button page-item previous">
                <a href="/Boss/send_status/{{ status }}/{{ job_list.next_page_number }}/" class="page-link">下一页</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

{% block script %}
    <script>
        // --------------------------------------------查看后改变状态--------------------------------------
        $(".resume").each(
            function () {
                $(this).click(
                    function () {
                        var check_id = $(this).attr("check_id");
                        $.ajax(
                            {
                                url: "/Boss/operate/",
                                type: "post",
                                data: {
                                    "check_id": check_id,
                                    "csrfmiddlewaretoken": '{{ csrf_token }}'
                                },
                                success: function (data) {
                                    console.log(data["msg"]);

                                    {#window.location.reload();  // 重新加载#}
                                },
                                error: function (error) {
                                    console.log(error);
                                }
                            }
                        )

                    }
                )
            }
        );


    </script>
{% endblock %}

job/Boss/templates/boss/job_list.html
{% extends "boss/base.html" %}
{% block title %}
    职位状态页
{% endblock %}
{% block content %}
    <table class="table" style="text-align: center">
            <thead>
            <tr>
                <th>公司</th>
                <th>职位</th>
                <th>时间</th>
                <th>发布人</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for one in job_list %}

            <tr>
                <td>{{ one.j_company.c_name }}</td>
                <td>{{ one.job_name }}</td>
                <td>{{ one.time }}</td>
                <td>{{ one.b_boss.name }}</td>
                <td>{{ one.get_check_status_display }}</td>
                <td>
                   <a href="/Boss/check/?id={{ one.id }}">
                        <button class="btn btn-primary">查看/修改</button>
                   </a>
                    <button class="btn btn-google delete_job" d_id="{{ one.id }}">删除职位</button>
                </td>
            </tr>
            {% endfor %}
            </tbody>
    </table>

<!--分页paginator-->
<ul class="pagination" style="float: right;">
        {% if job_list.has_previous %}
            <li class="paginate_button page-item previous">
                <a href="/Boss/job_list/{{ status }}/{{ job_list.previous_page_number }}/" class="page-link">上一页</a>
            </li>
        {% endif %}
        {% for p in page_range %}
            {% if p == page %}
                <li class="paginate_button page-item previous active">
                    <a href="/Boss/job_list/{{ status }}/{{ p }}/" class="page-link">{{ p }}</a>
                </li>
            {% else %}
                <li class="paginate_button page-item previous">
                    <a href="/Boss/job_list/{{ status }}/{{ p }}/" class="page-link">{{ p }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if job_list.has_next %}
            <li class="paginate_button page-item previous">
                <a href="/Boss/job_list/{{ status }}/{{ job_list.next_page_number }}/" class="page-link">下一页</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

{% block script %}
    <script>
       <!--删除操作-->
    $(".delete_job").each(
            function () {
                $(this).click(
                    function () {
                        var d_id = $(this).attr("d_id");
                        $.ajax(
                            {
                                url: "/Boss/delete_job/",
                                type: "post",
                                data: {
                                    "d_id": d_id,
                                    "csrfmiddlewaretoken": '{{ csrf_token }}'
                                },
                                success: function (data) {
                                    alert(data["msg"]);

                                    window.location.reload();  // 重新加载
                                },
                                error: function (error) {
                                    console.log(error);
                                }
                            }
                        )

                    }
                )
            }
        );
    </script>
{% endblock %}

job/Boss/templates/boss/update_password.html
{% extends 'boss/base.html' %}
{% block title %}
    修改密码页
{% endblock %}

{% block content %}
    <form action="" method="post" style="text-align: center">
        {% csrf_token %}
        <table class="table table-bordered dataTable">
            <thead>
            <tr>
                <th colspan="2" style="font-size: 30px;">您可以在这里修改您的密码:</th>
            </tr>

            </thead>
            <tbody>
            <tr>
                <th>请输入修改后的密码：</th>
                <td><input name="update_password" type="password" value=""></td>
            </tr>
            <tr>
                <th>请再次输入修改后的密码：</th>
                <td><input name="update_password1" type="password" value=""></td>
            </tr>
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">确认修改</button>
    </form>
{% endblock %}