job/job/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',register),
    path('login/',login),
    path('forget/',forget),
    path('index/',index),
    path('Graduate/',include("Graduate.urls")),
    path('Boss/',include("Boss.urls")),
    path('Admins/',include("Admins.urls"))
]

job/Boss/models.py
from django.db import models

# Create your models here.

# 企业性质表
class C_type(models.Model):
	type = models.CharField(max_length=64,verbose_name="企业性质")

	class Meta:
		db_table = 'c_type'


# 企业表
# 经营状态
MANAGE_STATUS = (
	(0,"存续(开业、正常、登记)"),
	(1,"在业"),
	(2,"吊销"),
	(3,"注销"),
	(4,"迁出"),
	(5,"迁入"),
	(6,"停业"),
	(7,"清算"),
	)
# 职员人数
STAFF_NUM = (
	(0,"少于10人"),
	(1,"10-49人"),
	(2,"50-99人"),
	(3,"100-499人"),
	(4,"500-999人"),
	(5,"1000-9999人"),
	(6,"10000人以上")
)

class Company(models.Model):
	c_email = models.EmailField(verbose_name='企业邮箱')
	c_name = models.CharField(max_length=32, verbose_name='企业名')
	phone_number = models.CharField(max_length=11, verbose_name='企业电话')
	c_code = models.CharField(max_length=32,verbose_name='统一信用代码')
	c_legal = models.CharField(max_length=32,verbose_name='企业法人')
	c_photo = models.ImageField(upload_to='images', verbose_name='企业照片')
	# 注册资本,单位：万元
	c_money = models.IntegerField(verbose_name='注册资本')
	c_status = models.IntegerField(choices=MANAGE_STATUS,verbose_name='经营状态')
	c_time = models.DateField(verbose_name='成立时间')
	c_address = models.TextField(verbose_name='注册地址')
	c_scope = models.TextField(verbose_name='经营范围')
	c_website = models.TextField(verbose_name='公司官网')
	c_descript = models.TextField(verbose_name='公司简介')
	# 公司人员
	c_staff = models.IntegerField(null=True,blank=True,choices=STAFF_NUM,verbose_name='职员人数')
	# 外键公司性质
	c_type = models.ForeignKey(null=True,blank=True,to=C_type,on_delete=models.CASCADE)

	class Meta:
		db_table = 'company'

# 招聘者现工作岗位信息
# 在职信息
WORK_STATUS = (
	(0,'在职'),
	(1,'离职'),
	(2,'停职'),
)

# 招聘者表
class Boss(models.Model):
	email = models.EmailField(verbose_name='邮箱', default=0)
	password = models.CharField(max_length=32, verbose_name='密码')
	name = models.CharField(max_length=32, null=True, blank=True, verbose_name='招聘者名')
	## null 针对数据库，可以为空
	## blank针对表单，表示在表单中该字段可以不填，对数据库没有影响
	phone = models.CharField(max_length=11, null=True, blank=True, verbose_name='手机号')
	## type 中
	## 0 代表求职者
	## 1 代表企业
	## 2 代表管理员
	type = models.CharField(max_length=4,null=True, blank=True, verbose_name='类别')
	photo = models.ImageField(upload_to='images', null=True, blank=True, verbose_name='头像')
	age = models.IntegerField(null=True, blank=True, verbose_name='年龄')
	gender = models.CharField(max_length=4, null=True, blank=True, verbose_name='性别')
	address = models.TextField(null=True, blank=True, verbose_name='居住地')
	work_status = models.IntegerField(null=True, blank=True,choices=WORK_STATUS, verbose_name='在职信息')
	professional_title = models.CharField(null=True, blank=True, max_length=32, verbose_name='职称')
	work_experience = models.TextField(null=True, blank=True, verbose_name='工作经验')
	# 外键，对应公司
	b_company = models.ForeignKey(null=True,blank=True,to=Company,on_delete=models.CASCADE)

	class Meta:
		db_table = 'boss'

# 城市表
class City(models.Model):
	name = models.CharField(max_length=32)

	class Meta:
		db_table = 'city'


# 职位表
# 学历
EDUCATION = (
	(0,'大专'),
	(1,'本科'),
	(2,'硕士'),
	(3,'博士'),
)
# 审核状态
REVIEW_STATUS = (
	(0,"待审核"),
	(1,"审核中"),
	(2,"已发布"),
	(3,"审核未通过"),
	(4,"已删除"),
	)

class Job(models.Model):
	job_name = models.CharField(max_length=32, verbose_name='职位名称')
	job_address = models.TextField(verbose_name='工作地点')
	education = models.IntegerField(choices=EDUCATION,verbose_name='学历')
	pay = models.CharField(max_length=20,verbose_name='薪资')
	job_descript = models.TextField(null=True,blank=True,verbose_name='岗位详情')
	demand = models.TextField(verbose_name='任职要求')
	work_time = models.TextField(verbose_name='工作时间')
	# 发布时间
	time = models.DateTimeField(auto_now=True,null=True,blank=True,verbose_name='发布时间')
	# 职位诱惑/标签   注意：在文本框中必须以逗号分割
	job_label = models.TextField(verbose_name='标签')
	# 管理员审核状态
	check_status = models.IntegerField(null=True, blank=True, choices=REVIEW_STATUS, verbose_name="审核状态")
	# 外键，对应城市,改职位在哪个城市下
	city = models.ForeignKey(to=City,on_delete=models.CASCADE,default=1)
	# 外键，对应公司
	j_company = models.ForeignKey(to=Company,on_delete=models.CASCADE)
	# 外键，对应hr
	b_boss = models.ForeignKey(to=Boss,on_delete=models.CASCADE)

	class Meta:
		db_table = 'job'

# 职位下投递情况表
# 投递状态
SEND_STATUS = (
	(0,'未查看'),
	(1,'已查看'),
	(2,'已发送邀请'),
	(3,'邀请面试成功'),
	(4,'不合适'),
	(5,'邀请面试失败'),
	(6,'面试通过'),
	(7,'面试未通过'),
	(8,'录用通知已发送'),
)

class Job_table(models.Model):
	# 投递者
	h_name = models.ForeignKey(to="Graduate.Hunter",on_delete=models.CASCADE)
	# 职位名
	j_name = models.ForeignKey(to=Job,on_delete=models.CASCADE,null=True,blank=True)
	time = models.DateTimeField(verbose_name='投递时间')
	send_status = models.IntegerField(choices=SEND_STATUS,verbose_name='投递状态')

	class Meta:
		db_table = 'job_table'

job/Admins/templates/adm/adm_boss.html
{% extends "adm/base.html" %}
{% block title %}
    企业hr信息管理页面
{% endblock %}
{% block content %}
    <table class="table table-bordered" style="text-align: center">
        <tr>
            <th>企业hr编号</th>
            <th>企业hr</th>
            <th>所属公司</th>
            <th>操作</th>
        </tr>
        {% for one in page_obj %}
            <tr>

                <td>{{ one.id }}</td>
                <td>{{ one.name }}</td>
                <td>{{ one.b_company.c_name }}</td>
                <td>
                    <a href="/Admins/operation/?id={{ one.id }}&type={{ one.type }}">
                        <button class="btn btn-primary">查看/修改</button>
                    </a>
                    <button class="btn btn-google delete_user" d_id="{{ one.id }}" d_type="{{ one.type }}">删除用户</button>
                </td>
            </tr>
        {% endfor %}
    </table>

    <ul class="pagination" style="float: right">
        {% if page_obj.has_previous %}
            <li class="paginate_button page-item previous">
                <a href="/Admins/boss/{{ page_obj.previous_page_number }}/" class="page-link">上一页</a>
            </li>
        {% endif %}
        {% for p in page_range %}
            {% if p == page %}
                <li class="paginate_button page-item previous active">
                    <a href="/Admins/boss/{{ p }}/" class="page-link">{{ p }}</a>
                </li>
            {% else %}
                <li class="paginate_button page-item previous">
                    <a href="/Admins/boss/{{ p }}/" class="page-link">{{ p }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="paginate_button page-item previous">
                <a href="/Admins/boss/{{ page_obj.next_page_number }}/" class="page-link">下一页</a>
            </li>
        {% endif %}
    </ul>

{% endblock %}

{% block script %}
    <script>
    // --------------------------------------------删除--------------------------------------
        $(".delete_user").each(
            function () {
                $(this).click(
                    function () {
                        var d_id = $(this).attr("d_id");
                        var d_type = $(this).attr("d_type");
                        $.ajax(
                            {
                                url: "/Admins/delete/",
                                type: "post",
                                data: {
                                    "d_id": d_id,
                                    "d_type": d_type,
                                    "csrfmiddlewaretoken": '{{ csrf_token }}'
                                },
                                success: function (data) {
                                    alert(data["msg"]);

                                    window.location.reload();  // 重新加载
                                },
                                error: function (error) {
                                    console.log(error);
                                }
                            }
                        )

                    }
                )
            }
        );
    </script>
{% endblock %}

job/Admins/templates/adm/adm_check.html
{% extends "adm/base.html" %}
{% block title %}
    用户信息页面
{% endblock %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-bordered dataTable" style="text-align: center">
            <thead style="font-size: 30px;font-weight: bold">
            <tr>
                <td colspan="5">基本信息</td>
            </tr>
            </thead>
            <tr>
                <td rowspan="3" style="width: 300px;">
                    <img style="width: 300px;height:300px" src="/static/{{ member.photo }}" alt="">
                </td>
                <th>邮箱</th>
                <td><input type="text" name="email" value="{{ member.email }}" disabled></td>
                <th>用户名</th>
                <td><input type="text" name="name" value="{{ member.name }}" disabled></td>
            </tr>
            <tr>
                <th>手机号</th>
                <td><input type="text" name="phone" value="{{ member.phone }}" disabled></td>

                <th>年龄</th>
                <td><input type="text" name="age" value="{{ member.age }}" disabled></td>
            </tr>
            <tr>
                <th>性别</th>
                <td><input type="text" name="gender" value="{{ member.gender }}" disabled></td>
                <th>地址</th>
                <td><input type="text" name="address" value="{{ member.native }}" disabled></td>
            </tr>
            {% if member.type == "0" %}
                <tr>
                    <th colspan="2">修改密码</th>
                    <td colspan="3"><input type="password" name="password"></td>
                </tr>
            {% elif member.type == "1" %}
                <tr>
                    <th colspan="2">所属公司</th>
                    <td><input type="text" name="company" value="{{ member.b_company.c_name }}" disabled></td>
                    <th>在职信息</th>
                    <td><input type="text" name="work_status" value="{{ member.get_work_status_display }}" disabled>
                    </td>
                </tr>
                <tr>
                    <th colspan="2">职称</th>
                    <td><input type="text" name="professional_title" value="{{ member.professional_title }}" disabled>
                    </td>
                    <th>工作经验</th>
                    <td><input type="text" name="work_experience" value="{{ member.work_experience }}" disabled></td>
                </tr>
                <tr>
                    <th colspan="2">修改密码</th>
                    <td colspan="3"><input type="password" name="password"></td>
                </tr>
            {% endif %}
            <tr>
                <td colspan="5" style="text-align: center">
                    <input class="btn btn-primary " type="submit" value="修改信息">
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

job/Admins/templates/adm/adm_hunter.html
{% extends "adm/base.html" %}
{% block title %}
    求职者信息管理页面
{% endblock %}
{% block content %}
    <table class="table table-bordered" style="text-align: center">
        <tr>
            <th>求职者id</th>
            <th>求职者</th>
            <th>操作</th>
        </tr>
        {% for one in page_obj %}
            <tr>

                <td>{{ one.id }}</td>
                <td>{{ one.name }}</td>
                <td>
                    <a href="/Admins/operation/?id={{ one.id }}&type={{ one.type }}">
                        <button class="btn btn-primary">查看/修改</button>
                    </a>
                    <button class="btn btn-google delete_user" d_id="{{ one.id }}" d_type="{{ one.type }}">删除用户</button>
                </td>
            </tr>
        {% endfor %}
    </table>

    <ul class="pagination" style="float: right">
        {% if page_obj.has_previous %}
            <li class="paginate_button page-item previous">
                <a href="/Admins/hunter/{{ page_obj.previous_page_number }}/" class="page-link">上一页</a>
            </li>
        {% endif %}
        {% for p in page_range %}
            {% if p == page %}
                <li class="paginate_button page-item previous active">
                    <a href="/Admins/hunter/{{ p }}/" class="page-link">{{ p }}</a>
                </li>
            {% else %}
                <li class="paginate_button page-item previous">
                    <a href="/Admins/hunter/{{ p }}/" class="page-link">{{ p }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="paginate_button page-item previous">
                <a href="/Admins/hunter/{{ page_obj.next_page_number }}/" class="page-link">下一页</a>
            </li>
        {% endif %}
    </ul>

{% endblock %}

{% block script %}
    <script>
    // --------------------------------------------删除--------------------------------------
        $(".delete_user").each(
            function () {
                $(this).click(
                    function () {
                        var d_id = $(this).attr("d_id");
                        var d_type = $(this).attr("d_type");
                        $.ajax(
                            {
                                url: "/Admins/delete/",
                                type: "post",
                                data: {
                                    "d_id": d_id,
                                    "d_type": d_type,
                                    "csrfmiddlewaretoken": '{{ csrf_token }}'
                                },
                                success: function (data) {
                                    alert(data["msg"]);

                                    window.location.reload();  // 重新加载
                                },
                                error: function (error) {
                                    console.log(error);
                                }
                            }
                        )

                    }
                )
            }
        );
    </script>
{% endblock %}

job/Admins/templates/adm/adm_info.html
{% extends "adm/base.html" %}
{% block title %}
    管理员个人信息
{% endblock %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-bordered dataTable" style="text-align: center">
            <thead style="font-size: 30px;font-weight: bold">
            <tr>
                <td colspan="5">基本信息</td>
            </tr>
            </thead>
            <tr>
                <td rowspan="3" style="width: 300px;">
                    <img style="width: 300px;height:300px" src="/static/{{ user.photo }}" alt="">
                    <input type="file" name="photo">
                </td>
                <th>邮箱</th>
                <td><input type="text" name="email" value="{{ user.email }}" disabled></td>
                <th>用户名</th>
                <td><input type="text" name="name" value="{{ user.name }}"></td>
            </tr>
            <tr>
                <th>手机号</th>
                <td><input type="text" name="phone" value="{{ user.phone }}"></td>

                <th>年龄</th>
                <td><input type="text" name="age" value="{{ user.age }}"></td>
            </tr>
            <tr>
                <th>性别</th>
                <td><input type="text" name="gender" value="{{ user.gender }}"></td>
                <th>地址</th>
                <td><input type="text" name="address" value="{{ user.address }}"></td>
            </tr>
            <tr>
                <td colspan="5" style="text-align: center">
                    <input class="btn btn-primary " type="submit" value="完善基本信息">
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

job/Admins/templates/adm/index.html
{% extends "adm/base.html" %}
{% block title %}
    管理员主页
{% endblock %}
{% block content %}
    <table class="table table-bordered dataTable" style="text-align: center">
        <thead>
        <tr>
            <th>公司</th>
            <th>职位名称</th>
            <th>发布人</th>
            <th>时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for one in job_list %}
            <tr>
                <td>{{ one.j_company.c_name }}</td>
                <td>{{ one.job_name }}</td>
                <td>{{ one.b_boss.name }}</td>
                <td>{{ one.time }}</td>
                <td>
                    <a href="/Admins/job_check/?id={{ one.id }}">
                        <button class="btn btn-primary">查看</button>
                    </a>
                    <button class="btn btn-success publish" fb_id="{{ one.id }}">发布</button>
                    <button class="btn btn-google refuse" bh_id="{{ one.id }}">驳回</button>
                    <button class="btn btn-danger delete" sc_id="{{ one.id }}">删除</button>
                </td>
            </tr>
        {% endfor %}

        </tbody>
        <tfoot></tfoot>
    </table>
       <!--分页paginator-->
    <ul class="pagination" style="float: right">
        {% if job_list.has_previous %}
            <li class="paginate_button page-item previous">
                <a href="/Admins/index/{{ job_list.previous_page_number }}/" class="page-link">上一页</a>
            </li>
        {% endif %}
        {% for p in page_range %}
            {% if p == page %}
                <li class="paginate_button page-item previous active">
                    <a href="/Admins/index/{{ p }}/" class="page-link">{{ p }}</a>
                </li>
            {% else %}
                <li class="paginate_button page-item previous">
                    <a href="/Admins/index/{{ p }}/" class="page-link">{{ p }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if job_list.has_next %}
            <li class="paginate_button page-item previous">
                <a href="/Admins/index/{{ job_list.next_page_number }}/" class="page-link">下一页</a>
            </li>
        {% endif %}
    </ul>

{% endblock %}

{% block script %}
    <script>
        //-----------------发布------------------
        $(".publish").each(
            function () {
                $(this).click(
                    function () {
                        var fb_id = $(this).attr("fb_id");
                        $.ajax(
                            {
                                url: "/Admins/check_operation/",
                                type: "post",
                                data: {
                                    "fb_id": fb_id,
                                    "csrfmiddlewaretoken": '{{ csrf_token }}'
                                },
                                success: function (data) {
                                    alert(data["msg"]);

                                    window.location.reload();  // 重新加载
                                },
                                error: function (error) {
                                    console.log(error);
                                }
                            }
                        )
                    }
                )
            }
        );

        //-----------------驳回------------------
        $(".refuse").each(
            function () {
                $(this).click(
                    function () {
                        var bh_id = $(this).attr("bh_id");
                        $.ajax(
                            {
                                url: "/Admins/check_operation/",
                                type: "post",
                                data: {
                                    "bh_id": bh_id,
                                    "csrfmiddlewaretoken": '{{ csrf_token }}'
                                },
                                success: function (data) {
                                    alert(data["msg"]);

                                    window.location.reload();  // 重新加载
                                },
                                error: function (error) {
                                    console.log(error);
                                }
                            }
                        )
                    }
                )
            }
        );


        //-----------------删除------------------
        $(".delete").each(
            function () {
                $(this).click(
                    function () {
                        var sc_id = $(this).attr("sc_id");
                        $.ajax(
                            {
                                url: "/Admins/check_operation/",
                                type: "post",
                                data: {
                                    "sc_id": sc_id,
                                    "csrfmiddlewaretoken": '{{ csrf_token }}'
                                },
                                success: function (data) {
                                    alert(data["msg"]);

                                    window.location.reload();  // 重新加载
                                },
                                error: function (error) {
                                    console.log(error);
                                }
                            }
                        )
                    }
                )
            }
        );
    </script>
{% endblock %}

job/Admins/templates/adm/job_check.html
{% extends "adm/base.html" %}
{% block title %}
    职位详情
{% endblock %}
{% block content %}
    <table class="table table-bordered dataTable" style="text-align: center;border:0">
        <thead style="font-size: 30px;font-weight: bold">
        <tr>
            <td colspan="6">职位信息</td>
        </tr>
        </thead>
        <tr>
            <th>职位名称</th>
            <td><input type="text" name="job_name" value="{{ job.job_name }}" disabled></td>
            <th>工作地点</th>
            <td><input type="text" name="job_address" value="{{ job.job_address }}" disabled></td>
            <th>学历</th>
            <td><input type="text" name="education" value="{{ job.get_education_display }}" disabled></td>
        </tr>
        <tr>
            <th>薪资</th>
            <td><input type="text" name="pay" value="{{ job.pay }}" disabled></td>
            <th>岗位详情</th>
            <td><textarea name="job_descript" disabled
                          class="form-control form-control-user">{{ job.job_descript }}</textarea></td>
            <th>任职要求</th>
            <td><textarea name="demand" disabled
                          class="form-control form-control-user">{{ job.demand }}</textarea></td>
        </tr>
        <tr>
            <th>工作时间</th>
            <td><textarea name="work_time" disabled
                          class="form-control form-control-user">{{ job.work_time }}</textarea></td>
            <th>标签</th>
            <td><textarea name="job_label" disabled
                          class="form-control form-control-user">{{ job.job_label }}</textarea></td>
            <th>城市</th>
            <td>
                <input type="text" name="city" value="{{ job.city.name }}" disabled>
            </td>
        </tr>
        <tr>
            {% if job.check_status < 2 %}
                <td colspan="2">
                    <button class="btn btn-success publish" fb_id="{{ job.id }}">发布职位</button>
                </td>
                <td colspan="2">
                    <button class="btn btn-google refuse" bh_id="{{ job.id }}" disabled>驳回请求</button>
                </td>
                <td colspan="2">
                    <button class="btn btn-danger delete" sc_id="{{ job.id }}">删除职位信息</button>
                </td>
            {% endif %}
            {% if job.check_status == 2 or job.check_status == 3 %}
                <td colspan="6">
                    <button class="btn btn-danger delete" sc_id="{{ job.id }}">删除职位信息</button>
                </td>
            {% endif %}
            {% if job.check_status == 4 %}
                <td colspan="6" style="font-size: 20px;color: red;text-align: center">该职位信息已被删除</td>
            {% endif %}
        </tr>
    </table>
{% endblock %}

{% block script %}
    <script>
        //-----------------发布------------------
        $(".publish").click(
            function () {
                var fb_id = $(".publish").attr("fb_id");
                $.ajax(
                    {
                        url: "/Admins/check_operation/",
                        type: "post",
                        data: {
                            "fb_id": fb_id,
                            "csrfmiddlewaretoken": '{{ csrf_token }}'
                        },
                        success: function (data) {
                            alert(data["msg"]);

                            window.location.reload();  // 重新加载
                        },
                        error: function (error) {
                            console.log(error);
                        }
                    }
                )
            }
        );

        //-----------------驳回------------------
        $(".refuse").click(
            function () {
                var bh_id = $(".refuse").attr("bh_id");
                $.ajax(
                    {
                        url: "/Admins/check_operation/",
                        type: "post",
                        data: {
                            "bh_id": bh_id,
                            "csrfmiddlewaretoken": '{{ csrf_token }}'
                        },
                        success: function (data) {
                            alert(data["msg"]);

                            window.location.reload();  // 重新加载
                        },
                        error: function (error) {
                            console.log(error);
                        }
                    }
                )
            }
        );

        //-----------------删除------------------
        $(".delete").click(
            function () {
                var sc_id = $(".delete").attr("sc_id");
                $.ajax(
                    {
                        url: "/Admins/check_operation/",
                        type: "post",
                        data: {
                            "sc_id": sc_id,
                            "csrfmiddlewaretoken": '{{ csrf_token }}'
                        },
                        success: function (data) {
                            alert(data["msg"]);

                            window.location.reload();  // 重新加载
                        },
                        error: function (error) {
                            console.log(error);
                        }
                    }
                )
            }
        );
    </script>
{% endblock %}

job/Admins/templates/adm/update_password.html
{% extends 'adm/base.html' %}
{% block title %}
    修改密码页
{% endblock %}

{% block content %}
    <form action="" method="post" style="text-align: center">
        {% csrf_token %}
        <table class="table table-bordered dataTable">
            <thead>
            <tr>
                <th colspan="2" style="font-size: 30px;">您可以在这里修改您的密码:</th>
            </tr>

            </thead>
            <tbody>
            <tr>
                <th>请输入修改后的密码：</th>
                <td><input name="update_password" type="password" value=""></td>
            </tr>
            <tr>
                <th>请再次输入修改后的密码：</th>
                <td><input name="update_password1" type="password" value=""></td>
            </tr>
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">确认修改</button>
    </form>
{% endblock %}