job/Graduate/urls.py
from django.urls import path,re_path
from Graduate.views import *

urlpatterns = [
	path('index/',index),
	path('userinfo/',userinfo),
	path('update/',update),
	path('company_info/',company_info),
	path('job_info/',job_info),
	path('operate/',operate),
	path('resume/',resume),
	path('logout/',logout),
	path('send_resume/',send_resume),
	re_path('resume_status/(?P<status>[012345678])/(?P<page>\d+)',resume_status),
]

job/job/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',register),
    path('login/',login),
    path('forget/',forget),
    path('index/',index),
    path('Graduate/',include("Graduate.urls")),
    path('Boss/',include("Boss.urls")),
    path('Admins/',include("Admins.urls"))
]

job/Boss/models.py
from django.db import models

# Create your models here.

# 企业性质表
class C_type(models.Model):
	type = models.CharField(max_length=64,verbose_name="企业性质")

	class Meta:
		db_table = 'c_type'


# 企业表
# 经营状态
MANAGE_STATUS = (
	(0,"存续(开业、正常、登记)"),
	(1,"在业"),
	(2,"吊销"),
	(3,"注销"),
	(4,"迁出"),
	(5,"迁入"),
	(6,"停业"),
	(7,"清算"),
	)
# 职员人数
STAFF_NUM = (
	(0,"少于10人"),
	(1,"10-49人"),
	(2,"50-99人"),
	(3,"100-499人"),
	(4,"500-999人"),
	(5,"1000-9999人"),
	(6,"10000人以上")
)

class Company(models.Model):
	c_email = models.EmailField(verbose_name='企业邮箱')
	c_name = models.CharField(max_length=32, verbose_name='企业名')
	phone_number = models.CharField(max_length=11, verbose_name='企业电话')
	c_code = models.CharField(max_length=32,verbose_name='统一信用代码')
	c_legal = models.CharField(max_length=32,verbose_name='企业法人')
	c_photo = models.ImageField(upload_to='images', verbose_name='企业照片')
	# 注册资本,单位：万元
	c_money = models.IntegerField(verbose_name='注册资本')
	c_status = models.IntegerField(choices=MANAGE_STATUS,verbose_name='经营状态')
	c_time = models.DateField(verbose_name='成立时间')
	c_address = models.TextField(verbose_name='注册地址')
	c_scope = models.TextField(verbose_name='经营范围')
	c_website = models.TextField(verbose_name='公司官网')
	c_descript = models.TextField(verbose_name='公司简介')
	# 公司人员
	c_staff = models.IntegerField(null=True,blank=True,choices=STAFF_NUM,verbose_name='职员人数')
	# 外键公司性质
	c_type = models.ForeignKey(null=True,blank=True,to=C_type,on_delete=models.CASCADE)

	class Meta:
		db_table = 'company'

# 招聘者现工作岗位信息
# 在职信息
WORK_STATUS = (
	(0,'在职'),
	(1,'离职'),
	(2,'停职'),
)

# 招聘者表
class Boss(models.Model):
	email = models.EmailField(verbose_name='邮箱', default=0)
	password = models.CharField(max_length=32, verbose_name='密码')
	name = models.CharField(max_length=32, null=True, blank=True, verbose_name='招聘者名')
	## null 针对数据库，可以为空
	## blank针对表单，表示在表单中该字段可以不填，对数据库没有影响
	phone = models.CharField(max_length=11, null=True, blank=True, verbose_name='手机号')
	## type 中
	## 0 代表求职者
	## 1 代表企业
	## 2 代表管理员
	type = models.CharField(max_length=4,null=True, blank=True, verbose_name='类别')
	photo = models.ImageField(upload_to='images', null=True, blank=True, verbose_name='头像')
	age = models.IntegerField(null=True, blank=True, verbose_name='年龄')
	gender = models.CharField(max_length=4, null=True, blank=True, verbose_name='性别')
	address = models.TextField(null=True, blank=True, verbose_name='居住地')
	work_status = models.IntegerField(null=True, blank=True,choices=WORK_STATUS, verbose_name='在职信息')
	professional_title = models.CharField(null=True, blank=True, max_length=32, verbose_name='职称')
	work_experience = models.TextField(null=True, blank=True, verbose_name='工作经验')
	# 外键，对应公司
	b_company = models.ForeignKey(null=True,blank=True,to=Company,on_delete=models.CASCADE)

	class Meta:
		db_table = 'boss'

# 城市表
class City(models.Model):
	name = models.CharField(max_length=32)

	class Meta:
		db_table = 'city'


# 职位表
# 学历
EDUCATION = (
	(0,'大专'),
	(1,'本科'),
	(2,'硕士'),
	(3,'博士'),
)
# 审核状态
REVIEW_STATUS = (
	(0,"待审核"),
	(1,"审核中"),
	(2,"已发布"),
	(3,"审核未通过"),
	(4,"已删除"),
	)

class Job(models.Model):
	job_name = models.CharField(max_length=32, verbose_name='职位名称')
	job_address = models.TextField(verbose_name='工作地点')
	education = models.IntegerField(choices=EDUCATION,verbose_name='学历')
	pay = models.CharField(max_length=20,verbose_name='薪资')
	job_descript = models.TextField(null=True,blank=True,verbose_name='岗位详情')
	demand = models.TextField(verbose_name='任职要求')
	work_time = models.TextField(verbose_name='工作时间')
	# 发布时间
	time = models.DateTimeField(auto_now=True,null=True,blank=True,verbose_name='发布时间')
	# 职位诱惑/标签   注意：在文本框中必须以逗号分割
	job_label = models.TextField(verbose_name='标签')
	# 管理员审核状态
	check_status = models.IntegerField(null=True, blank=True, choices=REVIEW_STATUS, verbose_name="审核状态")
	# 外键，对应城市,改职位在哪个城市下
	city = models.ForeignKey(to=City,on_delete=models.CASCADE,default=1)
	# 外键，对应公司
	j_company = models.ForeignKey(to=Company,on_delete=models.CASCADE)
	# 外键，对应hr
	b_boss = models.ForeignKey(to=Boss,on_delete=models.CASCADE)

	class Meta:
		db_table = 'job'

# 职位下投递情况表
# 投递状态
SEND_STATUS = (
	(0,'未查看'),
	(1,'已查看'),
	(2,'已发送邀请'),
	(3,'邀请面试成功'),
	(4,'不合适'),
	(5,'邀请面试失败'),
	(6,'面试通过'),
	(7,'面试未通过'),
	(8,'录用通知已发送'),
)

class Job_table(models.Model):
	# 投递者
	h_name = models.ForeignKey(to="Graduate.Hunter",on_delete=models.CASCADE)
	# 职位名
	j_name = models.ForeignKey(to=Job,on_delete=models.CASCADE,null=True,blank=True)
	time = models.DateTimeField(verbose_name='投递时间')
	send_status = models.IntegerField(choices=SEND_STATUS,verbose_name='投递状态')

	class Meta:
		db_table = 'job_table'

job/Graduate/models.py
from django.db import models
from Boss.models import Job_table


# Create your models here.

# 求职者用户表
class Hunter(models.Model):
	email = models.EmailField(verbose_name='邮箱', default=0)
	password = models.CharField(max_length=32, verbose_name='密码')
	name = models.CharField(null=True, blank=True, max_length=32, verbose_name='求职者名')
	phone = models.CharField(null=True, blank=True, max_length=11, verbose_name='手机号')
	## type 中
	## 0 代表求职者
	## 1 代表企业
	## 2 代表管理员
	type = models.CharField(max_length=4, verbose_name='类别')
	photo = models.ImageField(upload_to='images', null=True, blank=True, verbose_name='头像')
	age = models.IntegerField(null=True, blank=True, verbose_name='年龄')
	gender = models.CharField(null=True, blank=True, max_length=4, verbose_name='性别')
	native = models.CharField(max_length=32, null=True, blank=True, verbose_name='籍贯')
	# 在线简历
	expect_job = models.CharField(null=True, blank=True, max_length=64, verbose_name='意向岗位')
	city = models.CharField(null=True, blank=True, max_length=16, verbose_name='意向城市')
	salary = models.CharField(null=True, blank=True, max_length=16, verbose_name='期望薪资')
	education = models.TextField(null=True, blank=True, verbose_name='教育经历')
	project = models.TextField(null=True, blank=True, verbose_name='项目经历')
	school_experience = models.TextField(null=True, blank=True, verbose_name='在校经历')
	self_introduction = models.TextField(null=True, blank=True, verbose_name='自我介绍')
	skill = models.TextField(null=True, blank=True, verbose_name='相关技能')
	honor = models.TextField(null=True, blank=True, verbose_name='荣誉证书')
	# 上传简历
	resume = models.FileField(upload_to="resume",null=True,blank=True,verbose_name="简历")

	class Meta:
		db_table = "hunter"


# # 投递之后的进度表
# # 投递状态
# SEND_STATUS = (
# 	(0, '已投递'),
# 	(1, '被查看'),
# 	(2, '接受面试邀请'),
# 	(3, '不符合'),
# 	(4, '拒绝面试邀请'),
# 	(5, '面试通过'),
# 	(6, '面试未通过'),
# 	(7, '收到聘用协议'),
# )


# class Process(models.Model):
# 	# 职位、投递时间、状态
# 	name = models.ForeignKey(to=Job_table, on_delete=models.CASCADE)
# 	time = models.DateTimeField(verbose_name='投递时间')
# 	send_status = models.IntegerField(choices=SEND_STATUS, verbose_name='投递状态')
#
# 	class Meta:
# 		db_table = "process"

job/Graduate/views.py
import random, hashlib, requests, re, PyPDF2, datetime

from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from .models import *
from Boss.models import *

import geoip2.database


# Create your views here.

## 登录装饰器
def LoginVaild(func):
	def inner(request, *args, **kwargs):
		useremail = request.COOKIES.get('useremail')
		usertype = request.COOKIES.get("usertype")
		## 获取session
		session_useremail = request.session.get("useremail")
		session_type = request.session.get("usertype")
		if useremail and session_useremail and usertype and session_type and useremail == session_useremail and usertype == session_type and Hunter.objects.filter(
				email=useremail, type=usertype).first():
			return func(request, *args, **kwargs)
		else:
			return HttpResponseRedirect('/login/')

	return inner


# 获取当前登录用户
@LoginVaild
def get_user(request):
	useremail = request.COOKIES.get('useremail')
	usertype = request.COOKIES.get("usertype")
	user = Hunter.objects.filter(email=useremail, type=usertype).first()
	return user


# 获取当前ip所在城市
def get_city():
	# 通过requests请求ip网址，re匹配来获取外网ip，来获取城市名
	while True:
		url = "https://ip.cn/"
		headers = {
			'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36'
		}
		html_text = requests.get(url, headers=headers).text
		try:
			ip = re.search("<p>您现在的 IP：<code>(.*?)</code></p>", html_text)
			reader = geoip2.database.Reader('GeoLite2-City/GeoLite2-City.mmdb')
			data = reader.city(ip.group(1))
			city_name = data.city.names['zh-CN']
		except:
			city_name = ''
		if city_name:
			break
	city = City.objects.all()
	city_list = [one.name for one in city]
	if city_name in city_list:
		c_id = City.objects.get(name=city_name).id
	else:
		c_id = ""

	return city_name,c_id


## 密码加密
def setPassword(password):
	## 实现一个密码加密
	md5 = hashlib.md5()  ## 创建一个md5的实例对象
	md5.update(password.encode())  ## 进行加密
	result = md5.hexdigest()
	return result


## 登出
@LoginVaild
def logout(request):
	response = HttpResponseRedirect("/login/")
	keys = request.COOKIES.keys()
	for one in keys:
		response.delete_cookie(one)

	del request.session['useremail']
	del request.session['usertype']
	return response


# 主页
@LoginVaild
def index(request):
	user = get_user(request)
	ct_id = request.GET.get("ct_id")
	city = City.objects.all()
	if ct_id:
		city_name = City.objects.get(id=int(ct_id)).name
		job_obj = Job.objects.filter(check_status=2, city_id=int(ct_id)).order_by("time")
		if job_obj:
			job = job_obj
		else:
			job = Job.objects.filter(check_status=2).order_by("time")
	else:
		city_name,c_id = get_city()
			# 展示数据未职位
		# 说明定位城市存在，那么展示该城市职位
		if c_id:
			job_obj = Job.objects.filter(check_status=2, city_id=c_id).order_by("time")
			if job_obj:
				job = job_obj
			else:
				job = Job.objects.filter(check_status=2).order_by("time")
		else:
			city_name = city_name
			job = Job.objects.filter(check_status=2).order_by("time")
	return render(request, "graduate/index.html", locals())


# 个人信息页
@LoginVaild
def userinfo(request):
	user = get_user(request)
	resume = user
	if request.method == "POST":
		# 	# 获取表单信息，存入数据库
		data = request.POST
		user.name = data.get("name")
		user.phone = data.get("phone")
		user.age = data.get("age")
		user.gender = data.get("gender")
		user.native = data.get("address")
		user.photo = request.FILES.get('photo')
		user.resume = request.FILES.get("resume")
		user.save()

	return render(request, 'graduate/userinfo.html', locals())


# 修改密码
@LoginVaild
def update(request):
	user = get_user(request)
	if request.method == "POST":
		data = request.POST
		update = data.get("update_password")
		update1 = data.get("update_password1")
		if update and update1 and update == update1:
			user.password = setPassword(update)
			user.save()
	return render(request, 'graduate/update_password.html', locals())


# 在线编写简历
@LoginVaild
def resume(request):
	user = get_user(request)
	resume = user
	if request.method == "POST":
		# 	# 获取表单信息，存入数据库
		data = request.POST
		resume.expect_job = data.get("job")
		resume.city = data.get("city")
		resume.salary = data.get("salary")
		resume.education = data.get("education")
		resume.project = data.get("project")
		resume.school_experience = data.get("school_experience")
		resume.skill = data.get("skill")
		resume.honor = data.get("honor")
		resume.self_introduction = data.get("self_introduction")
		resume.save()

	return render(request, 'graduate/resume.html', locals())


# 公司信息页
def company_info(request):
	user = get_user(request)
	job_id = request.GET.get("job_id")
	print(job_id)
	c_id = request.GET.get("c_id")
	job = Job.objects.get(id=job_id)
	company = Company.objects.get(id=c_id)
	return render(request, 'graduate/company_info.html', locals())


# 职位信息页
def job_info(request):
	user = get_user(request)
	j_id = request.GET.get("j_id")
	job = Job.objects.get(id=j_id)
	desc = job.job_descript.split("；")
	demand = job.demand.split("；")
	try:
		jt = Job_table.objects.get(h_name_id=user.id,j_name=job)
	except:
		jt = ""
	return render(request, 'graduate/job_info.html', locals())


# 投递简历
def send_resume(request):
	user = get_user(request)
	j_id = request.GET.get("j_id")
	if request.method == "POST":
		type = request.POST.get("type")
		if type and type == "exist":
			t = Job_table()
			t.h_name_id = user.id
			t.j_name_id = Job.objects.get(id=int(j_id)).id
			t.time = datetime.datetime.now()
			t.send_status = 0
			t.save()
			result = {"code": 10000, "msg": "投递成功"}
		else:
			data = request.FILES.get("file")
			hunter = Hunter.objects.get(id=user.id)
			hunter.resume = data
			hunter.save()
			# 存进boss页面的Job_table表
			t = Job_table()
			t.h_name_id = user.id
			# 职位名
			t.j_name_id = Job.objects.get(id=int(j_id)).id
			t.time = datetime.datetime.now()
			t.send_status = 0
			t.save()
			result = {"code": 10000, "msg": "投递成功"}
	# hunter = Hunter.objects.get(id=user.id)
	# file = hunter.resume
	# filename = file.name
	# try:
	# 	result = filename.split('.')[1]
	# except:
	# 	result = "docx"
	# if result.lower() == "pdf":
	# 	# pdf文件
	# 	pdf_file = open('./static/{}'.format(filename), 'rb')
	# 	pdfReader = PyPDF2.PdfFileReader(pdf_file)
	#
	# 	pdfWriter = PyPDF2.PdfFileWriter()
	# 	for pageNum in range(pdfReader.numPages):
	# 		pageObj = pdfReader.getPage(pageNum)
	# 		pdfWriter.addPage(pageObj)
	# 	pdf_put = open('./static/upload_files/{}'.format(filename), 'wb')
	# 	pdfWriter.write(pdf_put)
	# 	pdf_put.close()
	# 	pdf_file.close()
	# else:
	# 	if file.size == "0":
	# 		message = "上传文件不能为空"
	# 	else:
	# 		# docx文件
	# 		with open("./static/upload_files/{}".format(filename),'wb+') as f:
	# 			string = file.read()
	# 			f.write(string)
	return JsonResponse(result)


def resume_status(request,status,page):
	page = int(page)
	user = get_user(request)

	if status == "0":
		# 已投递
		job_obj = Job_table.objects.filter(send_status__gte=0, h_name=user).order_by("time")
	elif status == "1":
		# 已查看
		job_obj = Job_table.objects.filter(send_status__gte=1, h_name=user).order_by("time")
	elif status == "2":
		# 收到面试邀请
		job_obj = Job_table.objects.filter(send_status__in=[2,3,5,6,7,8], h_name=user).order_by("time")
	elif status == "3":
		# 接受面试邀请
		job_obj = Job_table.objects.filter(send_status__in=[3,6,7,8], h_name=user).order_by("time")
	elif status == "4":
		# 不符合
		job_obj = Job_table.objects.filter(send_status=4, h_name=user).order_by("time")
	elif status == "5":
		## 拒绝面试邀请
		job_obj = Job_table.objects.filter(send_status=5, h_name=user).order_by("time")
	elif status == "6":
		## 面试通过
		job_obj = Job_table.objects.filter(send_status__in=[6,8], h_name=user).order_by("time")
	elif status == "7":
		## 面试未通过
		job_obj = Job_table.objects.filter(send_status=7, h_name=user).order_by("time")
	elif status == "8":
		## 收到录用通知
		job_obj = Job_table.objects.filter(send_status=8, h_name=user).order_by("time")
	job_all = Paginator(job_obj, 10)
	job_list = job_all.page(page)
	current_page = job_list.number
	start = current_page - 3
	if start < 1:
		start = 0
	end = current_page + 2
	if end > job_all.num_pages:
		end = job_all.num_pages
	if start == 0:
		end = 5
	page_range = job_all.page_range[start:end]


	return render(request,'graduate/resume_status.html',locals())

# 操作
def operate(request):
	if request.method == "POST":
		data = request.POST
		r_id = data.get("r_id")
		a_id = data.get("a_id")
		# 拒绝面试邀请
		if r_id:
			jt = Job_table.objects.get(id=r_id)
			jt.send_status = 5
			jt.save()
			result = {"code": 10000, "msg": "拒绝面试邀请成功"}
			# 接受面试邀请
		elif a_id:
			jt = Job_table.objects.get(id=a_id)
			jt.send_status = 3
			jt.save()
			result = {"code": 10000, "msg": "接受面试邀请"}
	return JsonResponse(result)

job/Graduate/templates/graduate/company_info.html
{% extends 'graduate/base.html' %}
{% block title %}
    公司信息页
{% endblock %}
{% block style %}
    <style>
        .point {
            display: inline-block;
            vertical-align: middle;
            width: 2px;
            height: 2px;
            margin: 0 7px;
            border-radius: 50%;
            background-color: rgba(255, 255, 255, .7)
        }

        .fd {
            float: left;
            overflow: hidden;
        }
        .gs{
            display: inline-block;
            color:#dda20a;
            margin: 0 5%;
            width: 15%;
        }
    </style>
{% endblock %}
{% block content %}
    <div style="margin:5% 10%;height:130px;background: #b7b9cc ">
        <div style="width: 80%;height: 120px;margin: 5px 0;" class="fd">
            <img src="/static/{{ company.c_photo }}" class="fd" style="height: 120px;width: 120px;border-radius: 8px">
            <div style="margin-left: 5%" class="fd">
                <p style="font-size: 30px;margin-bottom: 10px">{{ company.c_name }}</p>
                <p style="font-size: 14px;margin: 10px 0;">{{ company.c_descript }}</p>
                <p>{{ job.city.name }}<em class="point"></em>{{ company.c_staff }}<em class="point"></em>{{ company.c_type.type }}</p>
            </div>
        </div>
    </div>
    <!--信息页-->
    <div style="margin: 0 10%">

        <div>
            <div>
                <p style="font-size: 22px">{{ company.c_name }}</p>
                <p>官网：{{ company.c_website }}</p>
            </div>

            <div>
                <p>工商信息：</p>
                <div>
                    <p style="margin: 10px 0;width: 80%"><em class="gs">法人代表：</em><em>{{ company.c_legal }}</em></p>
                <p style="margin: 10px 0;width: 80%"><em class="gs">成立时间：</em><em>{{ company.c_time }}</em></p>
                <p style="margin: 10px 0;width: 80%"><em class="gs">注册地址：</em><em>{{ company.c_address }}</em></p>
                    <p style="margin: 10px 0;width: 80%"><em class="gs">注册资本：</em><em>{{ company.c_money }}万元</em></p>
                    <p style="margin: 10px 0;width: 80%"><em class="gs">经营状态：</em><em>{{ company.get_c_status_display }}</em></p>
                    <p style="margin: 10px 0;width: 80%"><em class="gs">统一信用代码：</em><em>{{ company.c_code }}</em></p>
                </div>

                <p style="margin: 10px 0;width: 80%"><em class="gs">经营范围：</em>{{ company.c_scope }}

            </div>
        </div>

    </div>
{% endblock %}

job/Graduate/templates/graduate/index.html
{% extends 'graduate/base.html' %}
{% block title %}
    首页
{% endblock %}
{% block style %}
    <style>
        .change {
            display: none;
            position: absolute;
            top: 200px;
            left: 400px;
            padding: 20px;
            border: 1px solid;
            background-color: white;
        }

        .city {
            float: left;
            list-style-type: none;
            width: 25%;
        }

        .city_list {
            overflow: hidden;
        }
    </style>
{% endblock %}

{% block search %}

    <p><span>{{ city_name }}</span>&nbsp&nbsp<a href="#oDiv"
                                                onclick="document.getElementById('oDiv').style.display='block'"><span
            style="font-size: 13px">[切换城市]</span></a></p>
    <div id="oDiv" class="change">
        <div>
            <strong style="font-size: 18px">亲爱的用户您好：</strong>
            <p></p>
            <p style="font-size: 14px">在这里您可以切换城市来寻找Job</p>
        </div>
        <hr>
        <p style="font-size: 14px">您可以切换到以下城市:</p>
        <ul class="city_list">
            {% for i in city %}
                <li class="city"><a href="/Graduate/index/?ct_id={{ i.id }}" class="btn">{{ i.name }}</a></li>
            {% endfor %}
        </ul>
        <p style="font-size: 14px">其他城市待开通......</p>
    </div>
{% endblock %}

{% block content %}
    <ul>
        {% for one in job %}
            <li style="list-style: none;height: 120px">
                <div style="background: #fff;width:80%;height: 110px;margin-left: 6%">
                    <div style="display: inline-block;float:left;width: 40%;height: 75px;overflow: hidden;margin-right: 5%;padding-top: 3px;">
                        <div style="padding-top: 5px">
                            <a href="/Graduate/job_info/?j_id={{ one.id }}">
                            <span style="width: 15%;padding-left: 3%;margin-right: 3%;font-size: 18px;">{{ one.job_name }}</span>
                                </a>
                            <span style="width: 5%;margin-right: 3%;">[&nbsp;{{ one.city.name }}&nbsp;]</span>
                            <span style="width:11%;font-size: 12px;">发布于{{ one.time }}</span>
                        </div>
                        <div style="padding-top: 5px"><span
                                style="padding-left: 3%;">{{ one.pay }}&nbsp;|&nbsp;{{ one.get_education_display }}</span>
                        </div>
                    </div>

                    <div style="display: inline-block;float:left;width: 40%;height:75px;margin-left: 5%;overflow: hidden">
                        <div style="padding-top: 5px">
                            <a href="/Graduate/company_info/?job_id={{ one.id }}&c_id={{ one.j_company_id }}"><span>{{ one.j_company.c_name }}</span></a>
                        </div>
                        <div style="padding-top: 5px">
                            <span style="font-size: 12px">{{ one.j_company.c_type.type }}&nbsp;|&nbsp;{{ one.j_company.get_c_staff_display }}</span>
                        </div>
                    </div>
                    <div style="float:right;overflow: hidden;width: 10%;height:80px;padding-top: 3px">
                        <img src="/static/{{ one.j_company.c_photo }}"
                             style="height: 73px;width: 73px;border: 1px solid #f3f5fb;border-radius: 9px">
                    </div>

                    <div style="height: 30px;width:100%;line-height: 30px;background: #fdf3d8;float: left;overflow: hidden">
                    <div style="height: 30px;width:100%;line-height: 30px;">
                        {% for one in one.job_label.split %}
                            {% if forloop.first %}
                                <span style="font-size: 12px;height: 20px;line-height:20px;margin: 5px 15px;border: 1px solid #169b6b;
        border-radius: 8px;display: inline-block;color: #b7b9cc;padding-left: 8px;padding-right: 8px">
            {{ one | slice:"2:-2" }}</span>
                            {% elif forloop.last %}
                                <span style="font-size: 12px;height: 20px;line-height:20px;margin: 5px 15px;border: 1px solid #169b6b;
        border-radius: 8px;display: inline-block;color: #b7b9cc;padding-left: 8px;padding-right: 8px">
            {{ one | slice:"1:-2" }}</span>
                            {% else %}
                                <span style="font-size: 12px;height: 20px;line-height:20px;margin: 5px 15px;border: 1px solid #169b6b;
        border-radius: 8px;display: inline-block;color: #b7b9cc;padding-left: 8px;padding-right: 8px">
            {{ one | slice:"1:-2" }}</span>
                            {% endif %}
                        {% endfor %}
                    </div>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

{% block script %}
    <script>
    </script>
{% endblock %}

job/Graduate/templates/graduate/process.html
{% extends 'graduate/base.html' %}
{% block title %}
    投递进程页
{% endblock %}

{% block content %}

{% endblock %}

job/Graduate/templates/graduate/update_password.html
{% extends 'graduate/base.html' %}
{% block title %}
    修改密码页
{% endblock %}

{% block content %}
    <form action="" method="post" style="text-align: center">
    {% csrf_token %}
        <table class="table table-bordered dataTable" >
            <thead>
            <tr>
                <th colspan="2" style="font-size: 30px;">您可以在这里修改您的密码:</th>
            </tr>

            </thead>
            <tbody>
                <tr>
                    <th>请输入修改后的密码：</th>
                    <td><input name="update_password" type="password" value=""></td>
                </tr>
                <tr>
                    <th>请再次输入修改后的密码：</th>
                    <td><input name="update_password1" type="password" value=""></td>
                </tr>
            </tbody>
        </table>
    <button type="submit" class="btn btn-primary">确认修改</button>
    </form>
{% endblock %}